spring:
  thymeleaf:
    mode:
      LEGACYHTML5
    check-template:
      false
    cache: false
  datasource:
    url: jdbc:mysql://47.92.72.146:3306/mg?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    initialize: true
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev
shiro:
  password:
    hash-iterations: 10 #默认加密次数,在密码匹配和注册两个地方使用
    algorithm-name: sha-1 #加密算法
server:
  port: 8888
  servlet:
    context-path: /api